### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by sheshap** [mlvlab/PointWOLF#2]
Hi Authors,

Thank you so much for releasing the code. Much appreciated.

Can you please post scripts/code used to visualize the examples (Fig. 1,2,3)?

Thanks in advance.

**Comment by blacktime14** [comment]
Hello @sheshap, sorry for the late reply.
Unfortunately, all visualization codes are gone.
We used PyVista (https://docs.pyvista.org/) for all visualizations.
Hope this helps at least a bit.

Best, Sihyeon.
