### ISSUE TITLE
Reproduced results on ModelNet40

### ISSUE THREAD

**Issue by jiawei-ren** [mlvlab/PointWOLF#3]
Reproduction procedure:

1. run the training command in README, e.g., `python main.py --exp_name=origin --model=dgcnn --num_points=1024 --k=20 --use_sgd=True`
2. run the evaluation command in README, e.g., `python main.py --exp_name=eval --model=dgcnn --num_points=1024 --k=20 --use_sgd=True --eval=True --model_path=${PATH}` 

Reproduced results on ModelNet40 are as follows:

- origin (DGCNN): **test acc: 0.926661**, test avg acc: 0.902744
- PointWOLF: **test acc: 0.924230**, test avg acc: 0.895413
- PointWOLF_AugTune: **test acc: 0.927877**, test avg acc: 0.893279

Results reported in the paper:

<img width="1648" alt="Screenshot 2022-01-03 at 11 34 16 AM" src="https://user-images.githubusercontent.com/72253125/147898004-32d7bc00-4fb7-425c-8ec4-37141c929eff.png">

The reproduced `PointWOLF`'s results (w/ or w/o AugTune) are slightly lower than the results reported in the original paper. Is that expected? Thanks.

**Comment by blacktime14** [comment]
Hello @jiawei-ren, thanks for your interest in our project.
The performance variance could happen due to random seed, which is a common problem to most point cloud backbone models.

Sorry for the late reply.
Best, Sihyeon.
